export const INCREASE_HEADCOUNTER="INCREASE_HEADCOUNTER";
export const INCREASE_CARD1_COUNTER="INCREASE_CARD1_COUNTER";
export const INCREASE_CARD2_COUNTER="INCREASE_CARD2_COUNTER";
export const INCREASE_CARD3_COUNTER="INCREASE_CARD3_COUNTER";
export const INCREASE_CARD4_COUNTER="INCREASE_CARD4_COUNTER";

